# Generated by Django 4.1.5 on 2023-06-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Img',
            field=models.ImageField(default='00', upload_to='gallery'),
        ),
    ]
